# Generated by Django 4.2.3 on 2023-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnoshop', '0002_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
